
#ifndef FMI_OOP_MYSTD_ENABLE_H
#define FMI_OOP_MYSTD_ENABLE_H

#ifdef FMI_JSON_PARSER_BUILD_WITH_MYSTD
#define FMI_OOP_USE_MYSTD_VARIANT
// #define FMI_OOP_USE_MYSTD_OPTIONAL
#endif

#endif // FMI_OOP_MYSTD_ENABLE_H
