
#ifndef FMI_OOP_MYSTD_ENABLE_H
#define FMI_OOP_MYSTD_ENABLE_H

#ifdef FMI_JSON_PARSER_BUILD_WITH_MYSTD
// #define FMI_OOP_USE_MYSTD_UNORDERED_MAP
#define FMI_OOP_USE_MYSTD_OPTIONAL
#define FMI_OOP_USE_MYSTD_UTILITY
#define FMI_OOP_USE_MYSTD_MEMORY
#endif

#endif // FMI_OOP_MYSTD_ENABLE_H
