name: ci
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE: Release
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04]
        cxx: [g++-11, clang++]
        cc: [gcc-11, clang]

    steps:
      - uses: actions/checkout@v2
      - name: Setup dependencies
        run: |
             sudo apt update
			 pip install -Iv conan==1.60.1
             sudo apt install gcc-11 g++-11 clang++ clang

      - name: Configure CMake
        env:
          CXX: ${{ matrix.cxx }}
        shell: bash
        working-directory: ${{github.workspace}}
        run: cmake -S. -DFMI_JSON_PARSER_BUILD_TESTS=ON -DFMI_JSON_PARSER_BUILD_APP=ON -DFMI_JSON_PARSER_BUILD_WITH_MYSTD=ON

      - name: Build
        working-directory: ${{github.workspace}}
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{github.workspace}}
        shell: bash
        run: ctest -C $BUILD_TYPE --no-tests=error
